#if !canImport(ObjectiveC)
import XCTest

extension PatternsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PatternsTests = [
        ("testCompilation", testCompilation),
    ]
}

extension RegexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegexTests = [
        ("testAtEnd", testAtEnd),
        ("testAtom", testAtom),
        ("testLookup", testLookup),
        ("testSplit", testSplit),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PatternsTests.__allTests__PatternsTests),
        testCase(RegexTests.__allTests__RegexTests),
    ]
}
#endif
